:arrow_up: Bump to Django 5
Also bump to Cython 3, the build error was fixed in later version, refs
https://github.com/mynotif/mynotif-backend/pull/115

Note that Django 5.1 is breaking djoser 2.2.3, the error is:
```
_pickle.PicklingError: Cannot pickle ResolverMatch
```
Refs https://github.com/sunscrapers/djoser/issues/842