:white_check_mark: Update broken unit tests
API changed between moto 4 and moto 5. The error was:
```
ImportError while importing test module 'mynotif-backend/src/nurse/tests/test_views.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/nurse/tests/test_views.py:13: in <module>
    from moto import mock_s3
E   ImportError: cannot import name 'mock_s3' from 'moto' (mynotif-backend/venv/lib/python3.11/site-packages/moto/__init__.py)
```
Also bumped GitHub Actions versions.

Also update formatting after black got updated and the Terraform code,
the error was:
```
│ Error: Cannot assume IAM Role
│
│ IAM Role ARN not set
│   on backend.tf line 4, in terraform:
│    4:   backend "s3" {
│ The following parameters have been deprecated. Replace them as follows:
│   * role_arn -> assume_role.role_arn
```