:wrench: Frontend domain Vercel
New domain: ordopro.fr

Also apply fixes related to terraform-aws-tfstate-backend, the errors were:
```
Warning: Deprecated Parameters

  on backend.tf line 4, in terraform:
   4:   backend "s3" {

The following parameters have been deprecated. Replace them as follows:
  * role_arn -> assume_role.role_arn

Error: Cannot assume IAM Role

IAM Role ARN not set
```